CREATE VIEW ALL_PART_TABLES AS
SELECT 
    TABLE_SCHEMA AS OWNER,
    TABLE_NAME,
    PARTITION_METHOD AS PARTITIONING_TYPE,
    COUNT(DISTINCT PARTITION_NAME) AS PARTITION_COUNT,
    LENGTH(PARTITION_EXPRESSION) - LENGTH(REPLACE(PARTITION_EXPRESSION, ',', '')) + 1 AS PARTITIONING_KEY_COUNT
FROM 
    information_schema.partitions
GROUP BY 
    TABLE_SCHEMA, 
    TABLE_NAME, 
    PARTITION_METHOD,
    PARTITION_EXPRESSION;