CREATE OR REPLACE VIEW ALL_TAB_PARTITIONS AS
SELECT
    TABLE_SCHEMA AS TABLE_OWNER,
    TABLE_NAME,
    PARTITION_NAME,

    MIN(PARTITION_ORDINAL_POSITION) AS PARTITION_POSITION,

    CASE
        WHEN MAX(PARTITION_DESCRIPTION) = 'MAXVALUE'
        THEN 'MAXVALUE'
        ELSE TRIM(BOTH '''' FROM MAX(PARTITION_DESCRIPTION))
    END AS HIGH_VALUE,

    LENGTH(
        CASE
            WHEN MAX(PARTITION_DESCRIPTION) = 'MAXVALUE'
            THEN 'MAXVALUE'
            ELSE TRIM(BOTH '''' FROM MAX(PARTITION_DESCRIPTION))
        END
    ) AS HIGH_VALUE_LENGTH,

    MAX(PARTITION_METHOD) AS PARTITIONING_TYPE,

    1 AS PARTITION_KEY_COUNT

FROM information_schema.PARTITIONS
WHERE PARTITION_NAME IS NOT NULL
GROUP BY
    TABLE_SCHEMA,
    TABLE_NAME,
    PARTITION_NAME;