-- MySQL view creation script.
-- Execute with: mysql < views.sql

CREATE OR REPLACE VIEW ALL_PART_KEY_COLUMNS AS
WITH part_tables AS (
    SELECT DISTINCT
        TABLE_SCHEMA,
        TABLE_NAME,
        PARTITION_EXPRESSION
    FROM information_schema.PARTITIONS
    WHERE PARTITION_NAME IS NOT NULL
      AND PARTITION_EXPRESSION IS NOT NULL
),
key_list AS (
    SELECT
        TABLE_SCHEMA AS OWNER,
        TABLE_NAME   AS NAME,
        TRIM(
          BOTH ')'
          FROM TRIM(
            BOTH '('
            FROM SUBSTRING_INDEX(PARTITION_EXPRESSION, '(', -1)
          )
        ) AS key_list
    FROM part_tables
)
SELECT
    k.OWNER,
    k.NAME,
    'TABLE' AS OBJECT_TYPE,
    TRIM(BOTH '`' FROM
         SUBSTRING_INDEX(
           SUBSTRING_INDEX(k.key_list, ',', n.n),
           ',', -1
         )
    ) AS COLUMN_NAME,
    n.n AS COLUMN_POSITION
FROM key_list k
JOIN (
    SELECT 1 n UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL
    SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL
    SELECT 7 UNION ALL SELECT 8
) n
  ON n.n <= 1 + LENGTH(k.key_list) - LENGTH(REPLACE(k.key_list, ',', ''))
WHERE k.key_list NOT REGEXP '[()]'
ORDER BY
    k.OWNER,
    k.NAME,
    COLUMN_POSITION;

CREATE OR REPLACE VIEW ALL_PART_TABLES AS
SELECT
    TABLE_SCHEMA AS OWNER,
    TABLE_NAME,
    PARTITION_METHOD AS PARTITIONING_TYPE,
    COUNT(DISTINCT PARTITION_NAME) AS PARTITION_COUNT,
    LENGTH(PARTITION_EXPRESSION) - LENGTH(REPLACE(PARTITION_EXPRESSION, ',', '')) + 1 AS PARTITIONING_KEY_COUNT
FROM information_schema.partitions
GROUP BY
    TABLE_SCHEMA,
    TABLE_NAME,
    PARTITION_METHOD,
    PARTITION_EXPRESSION;

CREATE OR REPLACE VIEW ALL_TAB_PARTITIONS AS
SELECT
    TABLE_SCHEMA AS TABLE_OWNER,
    TABLE_NAME,
    PARTITION_NAME,
    MIN(PARTITION_ORDINAL_POSITION) AS PARTITION_POSITION,
    CASE
        WHEN MAX(PARTITION_DESCRIPTION) = 'MAXVALUE'
        THEN 'MAXVALUE'
        ELSE TRIM(BOTH '''' FROM MAX(PARTITION_DESCRIPTION))
    END AS HIGH_VALUE,
    LENGTH(
        CASE
            WHEN MAX(PARTITION_DESCRIPTION) = 'MAXVALUE'
            THEN 'MAXVALUE'
            ELSE TRIM(BOTH '''' FROM MAX(PARTITION_DESCRIPTION))
        END
    ) AS HIGH_VALUE_LENGTH,
    MAX(PARTITION_METHOD) AS PARTITIONING_TYPE,
    1 AS PARTITION_KEY_COUNT
FROM information_schema.PARTITIONS
WHERE PARTITION_NAME IS NOT NULL
GROUP BY
    TABLE_SCHEMA,
    TABLE_NAME,
    PARTITION_NAME;
