rem ============================================================================
rem LICENSE
rem   Copyright (c) 2026 Oracle and/or its affiliates.
rem   Licensed under the Universal Permissive License (UPL), Version 1.0
rem   https://oss.oracle.com/licenses/upl/
rem
rem NAME
rem   oracle_ai_database_agent_tool.sql
rem
rem DESCRIPTION
rem   Installer script for Oracle AI Database Agent tools.
rem   (Select AI Agent / Oracle AI Database).
rem
rem   This script installs a consolidated PL/SQL package and registers
rem   AI Agent tools used by the Oracle AI Database Agent to refine
rem   Select AI NL2SQL operations via Select AI Agent
rem   (Oracle AI Database).
rem
rem RELEASE VERSION
rem   1.1
rem
rem RELEASE DATE
rem   6-Feb-2026
rem
rem MAJOR CHANGES IN THIS RELEASE
rem   - Run compatibility with Web SQL Developer
rem
rem SCRIPT STRUCTURE
rem   1. Initialization:
rem        - Grants
rem        - Configuration table setup
rem
rem   2. Package Deployment:
rem        - oracle_ai_data_retrieval_functions
rem          (package specification and body)
rem
rem   3. AI Tool Setup:
rem        - Creation of all Oracle AI Database Agent tools
rem
rem INSTALL INSTRUCTIONS
rem   1. Connect as ADMIN or a user with required privileges
rem   2. Run the script using websqldeveloper/SQL Developer
rem   3. Verify installation by checking tool registration
rem      and package compilation status.
rem
rem PARAMETERS
rem   SCHEMA_NAME (Required)
rem     Schema in which the package and tools will be created.
rem ----------------------------------------------------------------------------
rem
rem ============================================================================


SET SERVEROUTPUT ON
SET VERIFY OFF

-- ============================================================================
-- Installation Parameters
-- ============================================================================

-- First argument: Schema Name (Required)
VAR v_schema VARCHAR2(128)
EXEC :v_schema := '&SCHEMA_NAME';

PROMPT
PROMPT This installer registers database-native tools only.
PROMPT No additional configuration is required.
PROMPT


CREATE OR REPLACE PROCEDURE initialize_oracle_ai_data_retrieval_agent(
  p_install_schema_name IN VARCHAR2
)
IS
  l_schema_name         VARCHAR2(128);

  TYPE priv_list_t IS VARRAY(200) OF VARCHAR2(4000);
  l_priv_list CONSTANT priv_list_t := priv_list_t(
    'DBMS_CLOUD_AI',
    'DBMS_CLOUD_AI_AGENT'
  );

  ----------------------------------------------------------------------------
  -- Helper: grant execute on list of objects
  ----------------------------------------------------------------------------
  PROCEDURE execute_grants(p_schema IN VARCHAR2, p_objects IN priv_list_t) IS
    l_session_user VARCHAR2(128);
  BEGIN
    l_session_user := SYS_CONTEXT('USERENV', 'SESSION_USER');

    -- Avoid self-grant errors (ORA-01749) when installer schema == connected user.
    IF UPPER(p_schema) = UPPER(l_session_user) THEN
      DBMS_OUTPUT.PUT_LINE('Skipping grants for schema ' || p_schema ||
                           ' (same as session user).');
      RETURN;
    END IF;

    EXECUTE IMMEDIATE 'GRANT SELECT ON SYS.V_$PDBS TO ' || p_schema;
    FOR i IN 1 .. p_objects.COUNT LOOP
      BEGIN
        EXECUTE IMMEDIATE 'GRANT EXECUTE ON ' || p_objects(i) || ' TO ' || p_schema;
      EXCEPTION
        WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('Warning: failed to grant ' || p_objects(i) ||
                               ' to ' || p_schema || ' - ' || SQLERRM);
      END;
    END LOOP;
    
  EXCEPTION
    WHEN OTHERS THEN
      RAISE;
  END execute_grants;

BEGIN
  -- Validate schema name to avoid SQL injection when used in identifiers
  l_schema_name := DBMS_ASSERT.SIMPLE_SQL_NAME(p_install_schema_name);

  -- Grant required execute privileges using helper
  execute_grants(l_schema_name, l_priv_list);

  -- Create generic agent config table
  BEGIN
    EXECUTE IMMEDIATE
      'CREATE TABLE ' || l_schema_name || '.SELECTAI_AGENT_CONFIG (
         "ID"     NUMBER GENERATED BY DEFAULT AS IDENTITY,
         "KEY"    VARCHAR2(200) NOT NULL,
         "VALUE"  CLOB,
         "AGENT"  VARCHAR2(128) NOT NULL,
         CONSTRAINT SELECTAI_AGENT_CONFIG_PK PRIMARY KEY ("ID"),
         CONSTRAINT SELECTAI_AGENT_CONFIG_UK UNIQUE ("KEY","AGENT")
       )';
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE = -955 THEN
        NULL; -- already exists
      ELSE
        RAISE;
      END IF;
  END;

  DBMS_OUTPUT.PUT_LINE('initialize_oracle_ai_data_retrieval_agent completed for schema ' || l_schema_name);
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Fatal error in initialize_oracle_ai_data_retrieval_agent: ' || SQLERRM);
    RAISE;
  
END initialize_oracle_ai_data_retrieval_agent;
/

-------------------------------------------------------------------------------
-- Run the setup for the Oracle AI Database Agent tools.
-------------------------------------------------------------------------------
BEGIN

  initialize_oracle_ai_data_retrieval_agent(
    p_install_schema_name => :v_schema
  );

END;
/

BEGIN
  EXECUTE IMMEDIATE
    'ALTER SESSION SET CURRENT_SCHEMA = ' || :v_schema;
END;
/

------------------------------------------------------------------------
-- Package specification
------------------------------------------------------------------------
CREATE OR REPLACE PACKAGE oracle_ai_data_retrieval_functions
AS
  FUNCTION get_distinct_values_func(
    schema_name    IN VARCHAR2,
    table_name     IN VARCHAR2,
    column_name    IN VARCHAR2,
    match_pattern  IN VARCHAR2 DEFAULT NULL,
    match_type     IN VARCHAR2 DEFAULT NULL
  ) RETURN CLOB;
  
    FUNCTION get_range_values_func(
      user_prompt   IN CLOB
    ) RETURN CLOB; 
  
  FUNCTION get_current_timestamp(
    p_format IN VARCHAR2 DEFAULT 'YYYY-MM-DD HH24:MI:SS.FF'
  ) RETURN CLOB;
  
  FUNCTION runsql_func(
        user_prompt   IN CLOB
  ) RETURN CLOB;
  
  FUNCTION generate_chart_func(
    chart_prompt IN CLOB
  ) RETURN CLOB;

END oracle_ai_data_retrieval_functions;
/

------------------------------------------------------------------------
-- Package body
------------------------------------------------------------------------
CREATE OR REPLACE PACKAGE BODY oracle_ai_data_retrieval_functions
AS
    FUNCTION get_distinct_values_func (
        schema_name    IN VARCHAR2,
        table_name     IN VARCHAR2,
        column_name    IN VARCHAR2,
        match_pattern  IN VARCHAR2 DEFAULT NULL,
        match_type     IN VARCHAR2 DEFAULT NULL
    ) RETURN CLOB IS
        l_sql         VARCHAR2(4000);
        l_result      CLOB;
        l_data_type   VARCHAR2(128);
        max_length    PLS_INTEGER := 32767;
        l_match_type  VARCHAR2(10);
        l_threshold   NUMBER := 50; -- fuzzy similarity threshold (0–100)
    BEGIN
        -- Fetch column data type
        l_sql := 'SELECT data_type FROM all_tab_columns
                   WHERE owner = :1
                     AND table_name = :2
                     AND column_name = :3';
        EXECUTE IMMEDIATE l_sql INTO l_data_type
            USING schema_name, table_name, column_name;
    
        -- Normalize match_type input
        IF TRIM(match_pattern) IS NOT NULL AND 
           NVL(LOWER(TRIM(match_type)), 'NULL') NOT IN ('fuzzy', 'regex', 'exact') THEN
            l_match_type := 'fuzzy';
        ELSE
            l_match_type := LOWER(TRIM(match_type));
        END IF;
    
        -- Main matching logic
        IF match_pattern IS NOT NULL AND LENGTH(TRIM(match_pattern)) > 0 THEN
            l_sql := 'SELECT JSON_ARRAYAGG(col RETURNING CLOB) FROM (' ||
                     'SELECT DISTINCT ' || DBMS_ASSERT.enquote_name(column_name) || ' AS col ' ||
                     'FROM ' || DBMS_ASSERT.sql_object_name(schema_name || '.' || table_name);
    
            CASE l_match_type
                WHEN 'fuzzy' THEN
                    l_sql := l_sql ||
                            ' WHERE FUZZY_MATCH(JARO_WINKLER, ' || DBMS_ASSERT.enquote_name(column_name) || ', :pattern) >= :threshold)';
                    EXECUTE IMMEDIATE l_sql INTO l_result USING match_pattern, l_threshold;
    
                WHEN 'exact' THEN
                    l_sql := l_sql ||
                            ' WHERE ' || DBMS_ASSERT.enquote_name(column_name) || ' = :pattern)';
                    EXECUTE IMMEDIATE l_sql INTO l_result USING match_pattern;
    
                WHEN 'regex' THEN
                    l_sql := l_sql ||
                            ' WHERE REGEXP_LIKE(' || DBMS_ASSERT.enquote_name(column_name) || ', :pattern, ''i''))';
                    EXECUTE IMMEDIATE l_sql INTO l_result USING match_pattern;
    
                ELSE
                    raise_application_error(-20000, INITCAP(l_match_type) || ' match type is not supported.');
    
            END CASE;
        END IF;
    
        -- Fallback: return all distinct values
        IF l_result IS NULL THEN
            l_sql :=
              'SELECT JSON_ARRAYAGG(col RETURNING CLOB) FROM (' ||
              'SELECT DISTINCT ' || DBMS_ASSERT.enquote_name(column_name) || ' AS col ' ||
              'FROM ' || DBMS_ASSERT.sql_object_name(schema_name || '.' || table_name) || ')';
            EXECUTE IMMEDIATE l_sql INTO l_result;
        END IF;
    
        -- Truncate long results
        IF l_result IS NOT NULL AND DBMS_LOB.getlength(l_result) > max_length THEN
            l_result := SUBSTR(l_result, 1, max_length - 1)
                     || ',"notice":"Results truncated to '
                     || TO_CHAR(max_length) || ' characters."}';
        END IF;
    
        RETURN l_result;
    
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RETURN '{"error": "Column not found."}';
        WHEN OTHERS THEN
            RETURN '{"error": "' || REPLACE(SQLERRM, '"', '''') || '"}';
    END get_distinct_values_func;
    
    
    
    FUNCTION get_current_timestamp(
      p_format IN VARCHAR2 DEFAULT 'YYYY-MM-DD HH24:MI:SS.FF'
    ) RETURN CLOB
    IS
      l_timestamp TIMESTAMP := SYSTIMESTAMP;
      l_clob      CLOB;
    BEGIN
      l_clob := TO_CLOB(TO_CHAR(l_timestamp, p_format));
      RETURN l_clob;
    END;
    
    

    FUNCTION get_range_values_func(
      user_prompt   IN CLOB
    ) RETURN CLOB 
    IS
      l_sql CLOB;
      l_wrapped_sql CLOB;
      l_sql_result   CLOB;    
      l_json_result CLOB;
      l_obj         JSON_OBJECT_T:=new JSON_OBJECT_T();
      MAX_ROWS      CONSTANT PLS_INTEGER := 1000;
      SORRY_MESSAGE CONSTANT VARCHAR2(4000) := 'Sorry, unfortunately a valid SELECT statement could not be generated ';
      l_ai_profile   VARCHAR2(4000);
    BEGIN
      ------------------------------------------------------------------
      -- Fetch AI profile from SELECTAI_AGENT_CONFIG
      ------------------------------------------------------------------
      SELECT value
      INTO l_ai_profile
      FROM selectai_agent_config
      WHERE agent = 'ORACLE_AI_DATABASE_AGENT'
        AND key   = 'AGENT_AI_PROFILE';
        
        BEGIN
            l_sql := DBMS_CLOUD_AI.generate(prompt       => user_prompt,
                                            profile_name => l_ai_profile,
                                            action       => 'showsql');
        EXCEPTION
            WHEN OTHERS THEN
                RETURN 'Error Encountered: ' || SQLERRM;
        END;
        -- Check if SQL generation failed
        -- If failed, we directly give the generated sql back to LLM
        -- We want the LLM invoke the tool again with a better user prompt based on the sorry message
        IF INSTR(l_sql, SORRY_MESSAGE) = 1 THEN
            RETURN l_sql;
        END IF;
      -- Execute the SQL
    
        l_wrapped_sql := 'SELECT JSON_ARRAYAGG(JSON_OBJECT(* RETURNING CLOB) RETURNING CLOB) result ' ||
                        'FROM ( select * from (' || l_sql || ' ) FETCH FIRST ' || TO_CHAR(MAX_ROWS) || ' ROWS ONLY)';
        -- Execute the SQL
        EXECUTE IMMEDIATE l_wrapped_sql
            INTO l_sql_result;
        
        l_obj.put('sql_query',l_sql);
        
         IF l_sql_result is NULL THEN 
          l_obj.put('sql_result','No data found.');
        ELSE
          l_obj.put('sql_result',JSON_ARRAY_T.PARSE(l_sql_result));
        END IF;
        
        RETURN l_obj.to_clob();
     
    EXCEPTION
      WHEN NO_DATA_FOUND THEN
        RETURN '{"error":"AI profile not configured in SELECTAI_AGENT_CONFIG"}';
      WHEN OTHERS THEN
        RETURN 'Run SQL exception encountered: ' || SQLERRM ;
    END get_range_values_func;
    
    
    
    FUNCTION runsql_func(
        user_prompt   IN CLOB
    ) RETURN CLOB 
    IS
      l_sql CLOB;
      l_wrapped_sql CLOB;
      l_sql_result   CLOB;    
      l_json_result CLOB;
      l_obj         JSON_OBJECT_T:=new JSON_OBJECT_T();
      MAX_ROWS      CONSTANT PLS_INTEGER := 1000;
      SORRY_MESSAGE CONSTANT VARCHAR2(4000) := 'Sorry, unfortunately a valid SELECT statement could not be generated ';
      l_ai_profile   VARCHAR2(4000);
    BEGIN
      ------------------------------------------------------------------
      -- Fetch AI profile from SELECTAI_AGENT_CONFIG
      ------------------------------------------------------------------
      SELECT value
      INTO l_ai_profile
      FROM selectai_agent_config
      WHERE agent = 'ORACLE_AI_DATABASE_AGENT'
        AND key   = 'AGENT_AI_PROFILE';
        
    BEGIN
        l_sql := DBMS_CLOUD_AI.generate(prompt       => user_prompt,
                                        profile_name => l_ai_profile,
                                        action       => 'showsql');
    EXCEPTION
        WHEN OTHERS THEN
            RETURN 'Error Encountered: ' || SQLERRM;
    END;
    -- Check if SQL generation failed
    -- If failed, we directly give the generated sql back to LLM
    -- We want the LLM invoke the tool again with a better user prompt based on the sorry message
    IF INSTR(l_sql, SORRY_MESSAGE) = 1 THEN
        RETURN l_sql;
    END IF;
  -- Execute the SQL

    l_wrapped_sql := 'SELECT JSON_ARRAYAGG(JSON_OBJECT(* RETURNING CLOB) RETURNING CLOB) result ' ||
                    'FROM ( select * from (' || l_sql || ' ) FETCH FIRST ' || TO_CHAR(MAX_ROWS) || ' ROWS ONLY)';
    -- Execute the SQL
    EXECUTE IMMEDIATE l_wrapped_sql
        INTO l_sql_result;
    
    l_obj.put('sql_query',l_sql);
    
     IF l_sql_result is NULL THEN 
      l_obj.put('sql_result','No data found.');
    ELSE
      l_obj.put('sql_result',JSON_ARRAY_T.PARSE(l_sql_result));
    END IF;
    
    RETURN l_obj.to_clob();

 
    EXCEPTION
      WHEN NO_DATA_FOUND THEN
        RETURN '{"error":"AI profile not configured in SELECTAI_AGENT_CONFIG"}';
      WHEN OTHERS THEN
        RETURN 'Run SQL exception encountered: ' || SQLERRM ;
        
    END runsql_func;
    
    
    
    ------------------------------------------------------------------------------------
    -- generate_chart_func - to generate the charts
    ------------------------------------------------------------------------------------
    FUNCTION generate_chart_func(
      chart_prompt IN CLOB
    ) RETURN CLOB
    IS
      l_full_prompt  CLOB;
      l_result       CLOB;
      l_ai_profile   VARCHAR2(4000);
    BEGIN
      ------------------------------------------------------------------
      -- Fetch AI profile from SELECTAI_AGENT_CONFIG
      ------------------------------------------------------------------
      SELECT value
      INTO l_ai_profile
      FROM selectai_agent_config
      WHERE agent = 'ORACLE_AI_DATABASE_AGENT'
        AND key   = 'AGENT_AI_PROFILE';
    
      ------------------------------------------------------------------
      -- Build prompt
      ------------------------------------------------------------------
      l_full_prompt :=
           'You are a helpful assistant that generates Chart.js configurations in valid JSON format based on user prompts.' || CHR(10) ||
           '' || CHR(10) ||
           'Rules:' || CHR(10) ||
           '- Output ONLY a single valid JSON object or array of JSON objects. No markdown, no code blocks, no explanations.' || CHR(10) ||
           '- JSON must be syntactically valid. No comments. No text outside braces. No trailing commas.' || CHR(10) ||
           '- Use only these Chart.js types: "bar", "line", "pie", "doughnut", "radar", "scatter", "bubble", "polarArea".' || CHR(10) ||
           '- Ensure "labels" and "datasets" arrays are properly formatted.' || CHR(10) ||
           '- For "backgroundColor" and "borderColor", use ONLY colors from this palette and repeat as needed:' || CHR(10) ||
           '  ["#007bff", "#6c757d", "#28a745", "#ffc107", "#dc3545",' || CHR(10) ||
           '   "#20c997", "#6610f2", "#e83e8c", "#fd7e14", "#17a2b8",' || CHR(10) ||
           '   "#8bc34a", "#673ab7", "#03a9f4", "#ff9800", "#ff5722",' || CHR(10) ||
           '   "#4caf50", "#795548", "#607d8b", "#c2185b", "#343a40"]' || CHR(10) ||
           '- Do NOT output this palette again in the JSON. Just use these colors as values.' || CHR(10) ||
           '- Example of correct output:' || CHR(10) ||
           '{' || CHR(10) ||
           '  "type": "bar",' || CHR(10) ||
           '  "data": {' || CHR(10) ||
           '    "labels": ["A", "B", "C", "D", "E"],' || CHR(10) ||
           '    "datasets": [{' || CHR(10) ||
           '      "label": "Dataset 1",' || CHR(10) ||
           '      "data": [10, 20, 30, 40, 50],' || CHR(10) ||
           '      "backgroundColor": ["#007bff", "#6c757d", "#28a745", "#ffc107", "#dc3545"],' || CHR(10) ||
           '      "borderColor": ["#007bff", "#6c757d", "#28a745", "#ffc107", "#dc3545"],' || CHR(10) ||
           '      "borderWidth": 1' || CHR(10) ||
           '    }]' || CHR(10) ||
           '  },' || CHR(10) ||
           '  "options": {' || CHR(10) ||
           '    "responsive": true,' || CHR(10) ||
           '    "plugins": {' || CHR(10) ||
           '      "title": {"display": true, "text": "Sample Chart"}' || CHR(10) ||
           '    }' || CHR(10) ||
           '  }' || CHR(10) ||
           '}' || CHR(10) ||
           chart_prompt;
    
      ------------------------------------------------------------------
      -- Invoke Select AI using configured profile
      ------------------------------------------------------------------
      l_result :=
        DBMS_CLOUD_AI.generate(
          prompt       => l_full_prompt,
          profile_name => l_ai_profile,
          action       => 'chat'
        );
    
      RETURN l_result;
    
    EXCEPTION
      WHEN NO_DATA_FOUND THEN
        RETURN '{"error":"AI profile not configured in SELECTAI_AGENT_CONFIG"}';
      WHEN OTHERS THEN
        RETURN '{"error":"' || REPLACE(SQLERRM, '"', '\\"') || '"}';
    END generate_chart_func;

END oracle_ai_data_retrieval_functions;
/


------------------------------------------------------------------------------------------
-- This procedure installs or refreshes the NL2SQL data retrieval Agent tools in the
-- current schema. It drops any existing tool definitions and recreates them
-- pointing to the latest implementations in oracle_ai_data_retrieval_functions.
------------------------------------------------------------------------------------------

CREATE OR REPLACE PROCEDURE initialize_oracle_ai_data_retrieval_tools
IS
  PROCEDURE drop_tool_if_exists (tool_name IN VARCHAR2) IS
    l_tool_count NUMBER;
    l_sql        CLOB;
  BEGIN
    l_sql := 'SELECT COUNT(*) FROM USER_AI_AGENT_TOOLS WHERE TOOL_NAME = :1';
    EXECUTE IMMEDIATE l_sql INTO l_tool_count USING tool_name;
    IF l_tool_count > 0 THEN
      DBMS_CLOUD_AI_AGENT.DROP_TOOL(tool_name);
    END IF;
  END drop_tool_if_exists;
BEGIN
   drop_tool_if_exists(tool_name => 'DISTINCT_VALUES_CHECK');
   
   DBMS_CLOUD_AI_AGENT.create_tool(
    tool_name  => 'DISTINCT_VALUES_CHECK',
    description => 'Returns all unique values from a specified database column. Supports optional pattern matching to help filter results, making it easier to discover or troubleshoot specific data entries.',
    attributes => '{"instruction": "This tool returns distinct values from a specified column in a given table. ' ||
                    'If match_pattern is specified, then match_type must also be specified.' ||
                    'If both match_pattern and match_type are provided, the tool will filter distinct values using the specified matching technique.' ||
                    'If no matching values are found for the match_pattern, or if match_pattern was not specified, then the tool will return distinct values from the column.",
                    "function": "oracle_ai_data_retrieval_functions.get_distinct_values_func",
                    "tool_inputs": [{"name": "match_type",
                                     "mandatory": false,
                                     "description": "Type of filtering technique to use: ' ||
                                                    '1.fuzzy - uses FUZZY MATCH  string comparison in Oracle 23ai; ' ||
                                                    '2.exact - uses ''='' operator for exact matches; ' ||
                                                    '3.regex - uses REGEXP_LIKE for regular expression matching of the pattern."},
                                    {"name": "match_pattern",
                                    "mandatory": false,
                                    "description": "Pattern or keyword to filter values. If provided, matching_type must also be specified."}
                                    ]}'
  );
  
   drop_tool_if_exists(tool_name => 'SQL_TOOL');
   
   DBMS_CLOUD_AI_AGENT.create_tool(
    tool_name  => 'SQL_TOOL',
    description => 'Generates a SQL query from the provided natural language prompt and runs that query against your Oracle AI Database, returning the results. If no data is found, consider revising your prompt to be more descriptive.',
    attributes => '{"instruction": "This tool can access the data in database. It will take user question as user_prompt and generate a sql query, and then it will execute the sql query to get the result' ||
                                    ' If the result is 0 rows. It''s possible that there is an predicates issue. Please use RANGE_VALUES_CHECK for Numeric, DATE, or TIMESTAMP types or DISTINCT_VALUES_CHECK tool for other datatype columns to get all the distinct values and reinvoke the tool with a refined the user question", 
                    "function": "oracle_ai_data_retrieval_functions.runsql_func"}'
    );

   drop_tool_if_exists(tool_name => 'RANGE_VALUES_CHECK');

   DBMS_CLOUD_AI_AGENT.create_tool(
    tool_name  => 'RANGE_VALUES_CHECK',
    description => 'Retrieves the minimum and maximum values for a numeric, date, or timestamp column in your table. Useful for understanding data boundaries or refining searches.',
    attributes => '{
      "instruction": "This tool returns the minimum and maximum (range) values of a column in the given table. Only Numeric, DATE, or TIMESTAMP types columns are supported.",
      "function": "oracle_ai_data_retrieval_functions.get_range_values_func"
    }'
   );
   
   drop_tool_if_exists(tool_name => 'GENERATE_CHART');

   DBMS_CLOUD_AI_AGENT.create_tool(
    tool_name  => 'GENERATE_CHART',
    description => 'Creates charts or visualizations based on your data and preferences. Specify chart type, underlying data, and labels to generate formatted HTML or image output for display.',
    attributes => '{"instruction": "Use this tool when you need to generate a chart, graph, or visualization based on data. Provide a detailed prompt describing the chart type, data, labels, titles, and any other details. The tool will return formatted HTML for embedding the chart in the response.", 
                    "function": "oracle_ai_data_retrieval_functions.generate_chart_func"}'
   );

  DBMS_OUTPUT.PUT_LINE('initialize_oracle_ai_data_retrieval_tools completed.');
  
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error in initialize_oracle_ai_data_retrieval_tools: ' || SQLERRM);
    RAISE;
    
END initialize_oracle_ai_data_retrieval_tools;
/

-------------------------------------------------------------------------------
-- Call the procedure to (re)create all Oracle AI Database Agent tools
-------------------------------------------------------------------------------
BEGIN
  initialize_oracle_ai_data_retrieval_tools;
END;
/

alter session set current_schema = ADMIN;
