rem ============================================================================
rem LICENSE
rem   Copyright (c) 2026 Oracle and/or its affiliates.
rem   Licensed under the Universal Permissive License (UPL), Version 1.0
rem   https://oss.oracle.com/licenses/upl/
rem
rem NAME
rem   database_quality_check_tools.sql
rem
rem DESCRIPTION
rem   Installer script for Data Quality Select AI tools.
rem
rem RELEASE VERSION
rem   1.0
rem
rem RELEASE DATE
rem   18-May-2026
rem ============================================================================

SET SERVEROUTPUT ON
SET VERIFY OFF

VAR v_schema VARCHAR2(128)
EXEC :v_schema := '&SCHEMA_NAME';

CREATE OR REPLACE PROCEDURE initialize_data_quality_agent(
  p_install_schema_name IN VARCHAR2
)
IS
  l_schema_name VARCHAR2(128);

  TYPE priv_list_t IS VARRAY(20) OF VARCHAR2(4000);
  l_priv_list CONSTANT priv_list_t := priv_list_t(
    'DBMS_CLOUD_AI_AGENT',
    'DBMS_CLOUD_AI',
    'DBMS_CLOUD'
  );

  PROCEDURE execute_grants(p_schema IN VARCHAR2, p_objects IN priv_list_t) IS
    l_session_user VARCHAR2(128);
  BEGIN
    l_session_user := SYS_CONTEXT('USERENV', 'SESSION_USER');

    IF UPPER(p_schema) = UPPER(l_session_user) THEN
      DBMS_OUTPUT.PUT_LINE('Skipping grants for schema ' || p_schema ||
                           ' (same as session user).');
      RETURN;
    END IF;

    FOR i IN 1 .. p_objects.COUNT LOOP
      BEGIN
        EXECUTE IMMEDIATE 'GRANT EXECUTE ON ' || p_objects(i) || ' TO ' || p_schema;
      EXCEPTION
        WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('Warning: failed to grant ' || p_objects(i) ||
                               ' to ' || p_schema || ' - ' || SQLERRM);
      END;
    END LOOP;
  END execute_grants;
BEGIN
  l_schema_name := DBMS_ASSERT.SIMPLE_SQL_NAME(p_install_schema_name);

  execute_grants(l_schema_name, l_priv_list);

  BEGIN
    EXECUTE IMMEDIATE
      'CREATE TABLE ' || l_schema_name || '.SELECTAI_AGENT_CONFIG (
         "ID"     NUMBER GENERATED BY DEFAULT AS IDENTITY,
         "KEY"    VARCHAR2(200) NOT NULL,
         "VALUE"  CLOB,
         "AGENT"  VARCHAR2(128) NOT NULL,
         CONSTRAINT SELECTAI_AGENT_CONFIG_PK PRIMARY KEY ("ID"),
         CONSTRAINT SELECTAI_AGENT_CONFIG_UK UNIQUE ("KEY","AGENT")
       )';
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE != -955 THEN
        RAISE;
      END IF;
  END;

  DBMS_OUTPUT.PUT_LINE('initialize_data_quality_agent completed for schema ' ||
                       l_schema_name);
END initialize_data_quality_agent;
/

BEGIN
  initialize_data_quality_agent(:v_schema);
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER SESSION SET CURRENT_SCHEMA = ' || :v_schema;
END;
/

BEGIN
  BEGIN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE DQ_RUN_HISTORY$(
        run_id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        owner_name          VARCHAR2(128) NOT NULL,
        table_name          VARCHAR2(128) NOT NULL,
        run_ts              TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
        quality_score       NUMBER,
        null_rate_pct       NUMBER,
        duplicate_rate_pct  NUMBER,
        outlier_rate_pct    NUMBER,
        drift_score_pct     NUMBER,
        worst_severity      VARCHAR2(20),
        details             CLOB
      )
    ]';
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE != -955 THEN
        RAISE;
      END IF;
  END;

  BEGIN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE DQ_FINDINGS$(
        issue_id             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        run_id               NUMBER,
        owner_name           VARCHAR2(128) NOT NULL,
        table_name           VARCHAR2(128) NOT NULL,
        issue_type           VARCHAR2(64) NOT NULL,
        column_name          VARCHAR2(128),
        severity             VARCHAR2(20) NOT NULL,
        issue_value          NUMBER,
        threshold_value      NUMBER,
        recommendation       CLOB,
        generated_fix_sql    CLOB,
        status               VARCHAR2(30) DEFAULT 'OPEN',
        created_at           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
        CONSTRAINT dq_findings_run_fk FOREIGN KEY (run_id)
          REFERENCES DQ_RUN_HISTORY$(run_id)
      )
    ]';
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE != -955 THEN
        RAISE;
      END IF;
  END;

  BEGIN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE DQ_OML_MONITORS$(
        monitor_name       VARCHAR2(256) PRIMARY KEY,
        target_schema      VARCHAR2(128) NOT NULL,
        target_table       VARCHAR2(128) NOT NULL,
        baseline_expr      CLOB NOT NULL,
        newdata_expr       CLOB NOT NULL,
        oml_job_id         VARCHAR2(256),
        status             VARCHAR2(30) DEFAULT 'REGISTERED',
        last_run_ts        TIMESTAMP,
        last_run_response  CLOB,
        created_at         TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
      )
    ]';
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE != -955 THEN
        RAISE;
      END IF;
  END;
END;
/

CREATE OR REPLACE PACKAGE database_quality AUTHID CURRENT_USER AS
  FUNCTION profile_table(
    p_owner_name  IN VARCHAR2,
    p_table_name  IN VARCHAR2,
    sample_rows IN NUMBER DEFAULT 10000
  ) RETURN CLOB;

  FUNCTION detect_nulls(
    p_owner_name IN VARCHAR2,
    p_table_name IN VARCHAR2
  ) RETURN CLOB;

  FUNCTION detect_duplicates(
    p_owner_name      IN VARCHAR2,
    p_table_name      IN VARCHAR2,
    p_key_columns_csv IN VARCHAR2 DEFAULT NULL
  ) RETURN CLOB;

  FUNCTION detect_outliers(
    p_owner_name IN VARCHAR2,
    p_table_name IN VARCHAR2,
    p_z_limit    IN NUMBER DEFAULT 3
  ) RETURN CLOB;

  FUNCTION detect_drift(
    p_owner_name      IN VARCHAR2,
    p_table_name      IN VARCHAR2,
    p_baseline_days   IN NUMBER DEFAULT 30,
    p_current_days    IN NUMBER DEFAULT 7,
    p_drift_threshold IN NUMBER DEFAULT 20
  ) RETURN CLOB;

  FUNCTION generate_quality_rules(
    p_owner_name IN VARCHAR2,
    p_table_name IN VARCHAR2
  ) RETURN CLOB;

  FUNCTION evaluate_quality_score(
    owner_name IN VARCHAR2,
    table_name IN VARCHAR2
  ) RETURN CLOB;

  FUNCTION list_quality_issues(
    p_owner_name     IN VARCHAR2,
    p_table_name     IN VARCHAR2,
    p_severity_level IN VARCHAR2 DEFAULT NULL
  ) RETURN CLOB;

  FUNCTION suggest_remediation(
    owner_name IN VARCHAR2,
    table_name IN VARCHAR2
  ) RETURN CLOB;

  FUNCTION apply_remediation(
    p_owner_name   IN VARCHAR2,
    p_table_name   IN VARCHAR2,
    p_issue_id     IN NUMBER,
    p_execute_mode IN VARCHAR2 DEFAULT 'PREVIEW',
    p_approval_code IN VARCHAR2 DEFAULT NULL
  ) RETURN CLOB;

  FUNCTION setup_oml_data_monitoring(
    p_monitor_name IN VARCHAR2,
    p_target_schema IN VARCHAR2,
    p_target_table IN VARCHAR2,
    p_baseline_expr IN VARCHAR2,
    p_newdata_expr IN VARCHAR2
  ) RETURN CLOB;

  FUNCTION run_oml_data_monitoring(
    p_monitor_name IN VARCHAR2
  ) RETURN CLOB;
END database_quality;
/

CREATE OR REPLACE PACKAGE BODY database_quality AS
  FUNCTION quote_ident(p_name IN VARCHAR2) RETURN VARCHAR2 IS
  BEGIN
    RETURN DBMS_ASSERT.ENQUOTE_NAME(UPPER(TRIM(p_name)), FALSE);
  END quote_ident;

  FUNCTION full_table_name(p_owner IN VARCHAR2, p_table IN VARCHAR2) RETURN VARCHAR2 IS
  BEGIN
    RETURN quote_ident(p_owner) || '.' || quote_ident(p_table);
  END full_table_name;

  FUNCTION severity_rank(p_severity IN VARCHAR2) RETURN NUMBER IS
  BEGIN
    RETURN CASE UPPER(NVL(TRIM(p_severity), 'LOW'))
      WHEN 'CRITICAL' THEN 4
      WHEN 'HIGH' THEN 3
      WHEN 'MEDIUM' THEN 2
      ELSE 1
    END;
  END severity_rank;

  FUNCTION severity_name(p_rank IN NUMBER) RETURN VARCHAR2 IS
  BEGIN
    RETURN CASE
      WHEN p_rank >= 4 THEN 'CRITICAL'
      WHEN p_rank = 3 THEN 'HIGH'
      WHEN p_rank = 2 THEN 'MEDIUM'
      ELSE 'LOW'
    END;
  END severity_name;

  FUNCTION get_cfg_value(p_key IN VARCHAR2) RETURN CLOB IS
    l_val CLOB;
  BEGIN
    SELECT value
      INTO l_val
      FROM SELECTAI_AGENT_CONFIG
     WHERE UPPER(agent) = 'DATA_QUALITY'
       AND UPPER(key) = UPPER(p_key);
    RETURN l_val;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      RETURN NULL;
  END get_cfg_value;

  FUNCTION is_safe_remediation_sql(
    p_sql         IN CLOB,
    p_owner_name  IN VARCHAR2,
    p_table_name  IN VARCHAR2
  ) RETURN BOOLEAN IS
    l_sql CLOB := UPPER(TRIM(p_sql));
    l_target VARCHAR2(300) := UPPER(TRIM(p_owner_name)) || '.' || UPPER(TRIM(p_table_name));
  BEGIN
    IF l_sql IS NULL THEN
      RETURN FALSE;
    END IF;

    IF INSTR(l_sql, ';') > 0 OR INSTR(l_sql, '/*') > 0 OR INSTR(l_sql, '--') > 0 THEN
      RETURN FALSE;
    END IF;

    IF NOT (l_sql LIKE 'UPDATE %' OR l_sql LIKE 'DELETE %' OR l_sql LIKE 'MERGE %') THEN
      RETURN FALSE;
    END IF;

    IF l_sql LIKE '%DROP %' OR l_sql LIKE '%TRUNCATE %' OR l_sql LIKE '%ALTER %' OR
       l_sql LIKE '%CREATE %' OR l_sql LIKE '%GRANT %' THEN
      RETURN FALSE;
    END IF;

    IF INSTR(l_sql, l_target) = 0 THEN
      RETURN FALSE;
    END IF;

    RETURN TRUE;
  END is_safe_remediation_sql;

  PROCEDURE ensure_internal_tables IS
  BEGIN
    BEGIN
      EXECUTE IMMEDIATE q'[
        CREATE TABLE DQ_RUN_HISTORY$(
          run_id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          owner_name          VARCHAR2(128) NOT NULL,
          table_name          VARCHAR2(128) NOT NULL,
          run_ts              TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
          quality_score       NUMBER,
          null_rate_pct       NUMBER,
          duplicate_rate_pct  NUMBER,
          outlier_rate_pct    NUMBER,
          drift_score_pct     NUMBER,
          worst_severity      VARCHAR2(20),
          details             CLOB
        )
      ]';
    EXCEPTION
      WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
          RAISE;
        END IF;
    END;

    BEGIN
      EXECUTE IMMEDIATE q'[
        CREATE TABLE DQ_FINDINGS$(
          issue_id             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          run_id               NUMBER,
          owner_name           VARCHAR2(128) NOT NULL,
          table_name           VARCHAR2(128) NOT NULL,
          issue_type           VARCHAR2(64) NOT NULL,
          column_name          VARCHAR2(128),
          severity             VARCHAR2(20) NOT NULL,
          issue_value          NUMBER,
          threshold_value      NUMBER,
          recommendation       CLOB,
          generated_fix_sql    CLOB,
          status               VARCHAR2(30) DEFAULT 'OPEN',
          created_at           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
          CONSTRAINT dq_findings_run_fk FOREIGN KEY (run_id)
            REFERENCES DQ_RUN_HISTORY$(run_id)
        )
      ]';
    EXCEPTION
      WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
          RAISE;
        END IF;
    END;

    BEGIN
      EXECUTE IMMEDIATE q'[
        CREATE TABLE DQ_OML_MONITORS$(
          monitor_name       VARCHAR2(256) PRIMARY KEY,
          target_schema      VARCHAR2(128) NOT NULL,
          target_table       VARCHAR2(128) NOT NULL,
          baseline_expr      CLOB NOT NULL,
          newdata_expr       CLOB NOT NULL,
          oml_job_id         VARCHAR2(256),
          status             VARCHAR2(30) DEFAULT 'REGISTERED',
          last_run_ts        TIMESTAMP,
          last_run_response  CLOB,
          created_at         TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
        )
      ]';
    EXCEPTION
      WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
          RAISE;
        END IF;
    END;
  END ensure_internal_tables;

  FUNCTION profile_table(
    p_owner_name  IN VARCHAR2,
    p_table_name  IN VARCHAR2,
    sample_rows IN NUMBER DEFAULT 10000
  ) RETURN CLOB IS
    l_sql         VARCHAR2(32767);
    l_row_count   NUMBER := 0;
    l_col_count   NUMBER := 0;
    l_resp        JSON_OBJECT_T := JSON_OBJECT_T();
  BEGIN
    ensure_internal_tables;

    l_sql := 'SELECT COUNT(*) FROM ' || full_table_name(p_owner_name, p_table_name);
    EXECUTE IMMEDIATE l_sql INTO l_row_count;

    SELECT COUNT(*)
      INTO l_col_count
      FROM ALL_TAB_COLUMNS
     WHERE OWNER = UPPER(p_owner_name)
       AND TABLE_NAME = UPPER(p_table_name);

    l_resp.put('status', 'ok');
    l_resp.put('owner_name', UPPER(p_owner_name));
    l_resp.put('table_name', UPPER(p_table_name));
    l_resp.put('sample_rows_requested', NVL(sample_rows, 10000));
    l_resp.put('row_count', l_row_count);
    l_resp.put('column_count', l_col_count);
    l_resp.put('message', 'Table profiling completed.');
    RETURN l_resp.to_clob;
  EXCEPTION
    WHEN OTHERS THEN
      RETURN JSON_OBJECT('status' VALUE 'error',
                         'message' VALUE ('profile_table failed: ' || SQLERRM));
  END profile_table;

  FUNCTION detect_nulls(
    p_owner_name IN VARCHAR2,
    p_table_name IN VARCHAR2
  ) RETURN CLOB IS
    l_sql       VARCHAR2(32767);
    l_row_count NUMBER := 0;
    l_obj       JSON_OBJECT_T := JSON_OBJECT_T();
    l_arr       JSON_ARRAY_T := JSON_ARRAY_T();
    l_col       VARCHAR2(128);
    l_nulls     NUMBER;
    l_rate      NUMBER;
  BEGIN
    ensure_internal_tables;

    l_sql := 'SELECT COUNT(*) FROM ' || full_table_name(p_owner_name, p_table_name);
    EXECUTE IMMEDIATE l_sql INTO l_row_count;

    FOR r IN (
      SELECT COLUMN_NAME
      FROM ALL_TAB_COLUMNS
      WHERE OWNER = UPPER(p_owner_name)
        AND TABLE_NAME = UPPER(p_table_name)
      ORDER BY COLUMN_ID
    ) LOOP
      l_col := quote_ident(r.COLUMN_NAME);
      l_sql := 'SELECT COUNT(*) FROM ' || full_table_name(p_owner_name, p_table_name) ||
               ' WHERE ' || l_col || ' IS NULL';
      EXECUTE IMMEDIATE l_sql INTO l_nulls;

      l_rate := CASE WHEN l_row_count = 0 THEN 0 ELSE ROUND((l_nulls / l_row_count) * 100, 4) END;

      IF l_nulls > 0 THEN
        l_arr.append(JSON_OBJECT(
          'column_name' VALUE r.COLUMN_NAME,
          'null_count' VALUE l_nulls,
          'null_rate_pct' VALUE l_rate,
          'severity' VALUE CASE WHEN l_rate >= 20 THEN 'HIGH' WHEN l_rate >= 5 THEN 'MEDIUM' ELSE 'LOW' END
        ));
      END IF;
    END LOOP;

    l_obj.put('status', 'ok');
    l_obj.put('owner_name', UPPER(p_owner_name));
    l_obj.put('table_name', UPPER(p_table_name));
    l_obj.put('row_count', l_row_count);
    l_obj.put('issues', l_arr);
    RETURN l_obj.to_clob;
  EXCEPTION
    WHEN OTHERS THEN
      RETURN JSON_OBJECT('status' VALUE 'error',
                         'message' VALUE ('detect_nulls failed: ' || SQLERRM));
  END detect_nulls;

  FUNCTION detect_duplicates(
    p_owner_name      IN VARCHAR2,
    p_table_name      IN VARCHAR2,
    p_key_columns_csv IN VARCHAR2 DEFAULT NULL
  ) RETURN CLOB IS
    l_sql           VARCHAR2(32767);
    l_rows          NUMBER := 0;
    l_distinct_rows NUMBER := 0;
    l_dup_rows      NUMBER := 0;
    l_rate          NUMBER := 0;
    l_obj           JSON_OBJECT_T := JSON_OBJECT_T();
  BEGIN
    ensure_internal_tables;

    l_sql := 'SELECT COUNT(*) FROM ' || full_table_name(p_owner_name, p_table_name);
    EXECUTE IMMEDIATE l_sql INTO l_rows;

    IF p_key_columns_csv IS NULL OR TRIM(p_key_columns_csv) IS NULL THEN
      l_sql := 'SELECT COUNT(*) FROM (SELECT DISTINCT * FROM ' ||
               full_table_name(p_owner_name, p_table_name) || ')';
    ELSE
      l_sql := 'SELECT COUNT(*) FROM (SELECT DISTINCT ' || p_key_columns_csv ||
               ' FROM ' || full_table_name(p_owner_name, p_table_name) || ')';
    END IF;

    EXECUTE IMMEDIATE l_sql INTO l_distinct_rows;

    l_dup_rows := GREATEST(l_rows - l_distinct_rows, 0);
    l_rate := CASE WHEN l_rows = 0 THEN 0 ELSE ROUND((l_dup_rows / l_rows) * 100, 4) END;

    l_obj.put('status', 'ok');
    l_obj.put('owner_name', UPPER(p_owner_name));
    l_obj.put('table_name', UPPER(p_table_name));
    l_obj.put('row_count', l_rows);
    l_obj.put('distinct_row_count', l_distinct_rows);
    l_obj.put('duplicate_row_count', l_dup_rows);
    l_obj.put('duplicate_rate_pct', l_rate);
    l_obj.put('severity', CASE WHEN l_rate >= 10 THEN 'HIGH' WHEN l_rate >= 2 THEN 'MEDIUM' ELSE 'LOW' END);
    RETURN l_obj.to_clob;
  EXCEPTION
    WHEN OTHERS THEN
      RETURN JSON_OBJECT('status' VALUE 'error',
                         'message' VALUE ('detect_duplicates failed: ' || SQLERRM));
  END detect_duplicates;

  FUNCTION detect_outliers(
    p_owner_name IN VARCHAR2,
    p_table_name IN VARCHAR2,
    p_z_limit    IN NUMBER DEFAULT 3
  ) RETURN CLOB IS
    l_obj         JSON_OBJECT_T := JSON_OBJECT_T();
    l_arr         JSON_ARRAY_T := JSON_ARRAY_T();
    l_sql         VARCHAR2(32767);
    l_outlier_cnt NUMBER;
    l_row_count   NUMBER;
    l_rate        NUMBER;
  BEGIN
    ensure_internal_tables;

    l_sql := 'SELECT COUNT(*) FROM ' || full_table_name(p_owner_name, p_table_name);
    EXECUTE IMMEDIATE l_sql INTO l_row_count;

    FOR c IN (
      SELECT COLUMN_NAME
      FROM ALL_TAB_COLUMNS
      WHERE OWNER = UPPER(p_owner_name)
        AND TABLE_NAME = UPPER(p_table_name)
        AND DATA_TYPE IN ('NUMBER', 'FLOAT', 'BINARY_DOUBLE', 'BINARY_FLOAT')
      ORDER BY COLUMN_ID
    ) LOOP
      l_sql :=
        'WITH s AS (' ||
        '  SELECT ' || quote_ident(c.COLUMN_NAME) || ' v FROM ' || full_table_name(p_owner_name, p_table_name) ||
        '  WHERE ' || quote_ident(c.COLUMN_NAME) || ' IS NOT NULL' ||
        '), m AS (' ||
        '  SELECT AVG(v) mu, STDDEV(v) sigma FROM s' ||
        ')' ||
        ' SELECT COUNT(*) FROM s, m' ||
        ' WHERE m.sigma > 0 AND ABS((s.v - m.mu) / m.sigma) > :z';

      EXECUTE IMMEDIATE l_sql INTO l_outlier_cnt USING NVL(p_z_limit, 3);
      l_rate := CASE WHEN l_row_count = 0 THEN 0 ELSE ROUND((l_outlier_cnt / l_row_count) * 100, 4) END;

      IF l_outlier_cnt > 0 THEN
        l_arr.append(JSON_OBJECT(
          'column_name' VALUE c.COLUMN_NAME,
          'outlier_count' VALUE l_outlier_cnt,
          'outlier_rate_pct' VALUE l_rate,
          'severity' VALUE CASE WHEN l_rate >= 10 THEN 'HIGH' WHEN l_rate >= 3 THEN 'MEDIUM' ELSE 'LOW' END
        ));
      END IF;
    END LOOP;

    l_obj.put('status', 'ok');
    l_obj.put('owner_name', UPPER(p_owner_name));
    l_obj.put('table_name', UPPER(p_table_name));
    l_obj.put('issues', l_arr);
    RETURN l_obj.to_clob;
  EXCEPTION
    WHEN OTHERS THEN
      RETURN JSON_OBJECT('status' VALUE 'error',
                         'message' VALUE ('detect_outliers failed: ' || SQLERRM));
  END detect_outliers;

  FUNCTION detect_drift(
    p_owner_name      IN VARCHAR2,
    p_table_name      IN VARCHAR2,
    p_baseline_days   IN NUMBER DEFAULT 30,
    p_current_days    IN NUMBER DEFAULT 7,
    p_drift_threshold IN NUMBER DEFAULT 20
  ) RETURN CLOB IS
    l_hist_avg NUMBER := 0;
    l_curr     NUMBER := 0;
    l_change   NUMBER := 0;
    l_sql      VARCHAR2(32767);
    l_obj      JSON_OBJECT_T := JSON_OBJECT_T();
  BEGIN
    ensure_internal_tables;

    l_sql := q'[
      SELECT NVL(AVG(quality_score), 0)
      FROM DQ_RUN_HISTORY$
      WHERE owner_name = UPPER(:1)
        AND table_name = UPPER(:2)
        AND run_ts >= SYSTIMESTAMP - NUMTODSINTERVAL(:3, 'DAY')
        AND run_ts < SYSTIMESTAMP - NUMTODSINTERVAL(:4, 'DAY')
    ]';
    EXECUTE IMMEDIATE l_sql INTO l_hist_avg USING p_owner_name, p_table_name,
      NVL(p_baseline_days, 30), NVL(p_current_days, 7);

    l_sql := q'[
      SELECT NVL(AVG(quality_score), 0)
      FROM DQ_RUN_HISTORY$
      WHERE owner_name = UPPER(:1)
        AND table_name = UPPER(:2)
        AND run_ts >= SYSTIMESTAMP - NUMTODSINTERVAL(:3, 'DAY')
    ]';
    EXECUTE IMMEDIATE l_sql INTO l_curr USING p_owner_name, p_table_name,
      NVL(p_current_days, 7);

    IF l_hist_avg = 0 THEN
      l_change := 0;
    ELSE
      l_change := ROUND(((l_curr - l_hist_avg) / l_hist_avg) * 100, 4);
    END IF;

    l_obj.put('status', 'ok');
    l_obj.put('owner_name', UPPER(p_owner_name));
    l_obj.put('table_name', UPPER(p_table_name));
    l_obj.put('baseline_avg_score', l_hist_avg);
    l_obj.put('current_avg_score', l_curr);
    l_obj.put('drift_pct', l_change);
    l_obj.put('threshold_pct', NVL(p_drift_threshold, 20));
    l_obj.put('is_drift_flagged', CASE WHEN ABS(l_change) >= NVL(p_drift_threshold, 20) THEN 'true' ELSE 'false' END);
    RETURN l_obj.to_clob;
  EXCEPTION
    WHEN OTHERS THEN
      RETURN JSON_OBJECT('status' VALUE 'error',
                         'message' VALUE ('detect_drift failed: ' || SQLERRM));
  END detect_drift;

  FUNCTION generate_quality_rules(
    p_owner_name IN VARCHAR2,
    p_table_name IN VARCHAR2
  ) RETURN CLOB IS
    l_obj   JSON_OBJECT_T := JSON_OBJECT_T();
    l_rules JSON_ARRAY_T := JSON_ARRAY_T();
  BEGIN
    ensure_internal_tables;

    l_rules.append(JSON_OBJECT('rule_type' VALUE 'NOT_NULL',
                               'rule' VALUE 'Enforce NOT NULL for mandatory business columns after cleanup.'));
    l_rules.append(JSON_OBJECT('rule_type' VALUE 'UNIQUENESS',
                               'rule' VALUE 'Create unique constraints or indexes for natural/business keys.'));
    l_rules.append(JSON_OBJECT('rule_type' VALUE 'RANGE_CHECK',
                               'rule' VALUE 'Set acceptable min/max ranges for numeric measures.'));
    l_rules.append(JSON_OBJECT('rule_type' VALUE 'REFERENCE_INTEGRITY',
                               'rule' VALUE 'Apply FK constraints for parent-child relationships where applicable.'));

    l_obj.put('status', 'ok');
    l_obj.put('owner_name', UPPER(p_owner_name));
    l_obj.put('table_name', UPPER(p_table_name));
    l_obj.put('rules', l_rules);
    RETURN l_obj.to_clob;
  END generate_quality_rules;

  FUNCTION evaluate_quality_score(
    owner_name IN VARCHAR2,
    table_name IN VARCHAR2
  ) RETURN CLOB IS
    l_null_rate   NUMBER := 0;
    l_dup_rate    NUMBER := 0;
    l_out_rate    NUMBER := 0;
    l_drift_score NUMBER := 0;
    l_score       NUMBER := 100;
    l_sev_rank    NUMBER := 1;
    l_worst_sev   VARCHAR2(20) := 'LOW';
    l_run_id      NUMBER;
    l_obj         JSON_OBJECT_T := JSON_OBJECT_T();
    l_sql         VARCHAR2(32767);
    l_hist_avg    NUMBER := 0;
    l_curr_avg    NUMBER := 0;
    l_drift_pct   NUMBER := 0;
  BEGIN
    ensure_internal_tables;

    BEGIN
      l_sql := 'SELECT AVG(issue_value) FROM DQ_FINDINGS$ WHERE owner_name = UPPER(:1) AND table_name = UPPER(:2) AND issue_type = ''NULL_RATE'' AND status = ''OPEN''';
      EXECUTE IMMEDIATE l_sql INTO l_null_rate USING owner_name, table_name;
    EXCEPTION
      WHEN OTHERS THEN l_null_rate := 0;
    END;

    BEGIN
      l_sql := 'SELECT AVG(issue_value) FROM DQ_FINDINGS$ WHERE owner_name = UPPER(:1) AND table_name = UPPER(:2) AND issue_type = ''DUPLICATE_RATE'' AND status = ''OPEN''';
      EXECUTE IMMEDIATE l_sql INTO l_dup_rate USING owner_name, table_name;
    EXCEPTION
      WHEN OTHERS THEN l_dup_rate := 0;
    END;

    BEGIN
      l_sql := 'SELECT AVG(issue_value) FROM DQ_FINDINGS$ WHERE owner_name = UPPER(:1) AND table_name = UPPER(:2) AND issue_type = ''OUTLIER_RATE'' AND status = ''OPEN''';
      EXECUTE IMMEDIATE l_sql INTO l_out_rate USING owner_name, table_name;
    EXCEPTION
      WHEN OTHERS THEN l_out_rate := 0;
    END;

    BEGIN
      l_sql := 'SELECT MAX(severity) KEEP (DENSE_RANK LAST ORDER BY CASE severity WHEN ''LOW'' THEN 1 WHEN ''MEDIUM'' THEN 2 WHEN ''HIGH'' THEN 3 ELSE 4 END) FROM DQ_FINDINGS$ WHERE owner_name = UPPER(:1) AND table_name = UPPER(:2) AND status = ''OPEN''';
      EXECUTE IMMEDIATE l_sql INTO l_worst_sev USING owner_name, table_name;
    EXCEPTION
      WHEN OTHERS THEN l_worst_sev := 'LOW';
    END;

    l_null_rate := NVL(l_null_rate, 0);
    l_dup_rate := NVL(l_dup_rate, 0);
    l_out_rate := NVL(l_out_rate, 0);
    BEGIN
      l_sql := q'[
        SELECT NVL(AVG(quality_score), 0)
        FROM DQ_RUN_HISTORY$
        WHERE owner_name = UPPER(:1)
          AND table_name = UPPER(:2)
          AND run_ts >= SYSTIMESTAMP - NUMTODSINTERVAL(30, 'DAY')
          AND run_ts < SYSTIMESTAMP - NUMTODSINTERVAL(7, 'DAY')
      ]';
      EXECUTE IMMEDIATE l_sql INTO l_hist_avg USING owner_name, table_name;

      l_sql := q'[
        SELECT NVL(AVG(quality_score), 0)
        FROM DQ_RUN_HISTORY$
        WHERE owner_name = UPPER(:1)
          AND table_name = UPPER(:2)
          AND run_ts >= SYSTIMESTAMP - NUMTODSINTERVAL(7, 'DAY')
      ]';
      EXECUTE IMMEDIATE l_sql INTO l_curr_avg USING owner_name, table_name;

      IF l_hist_avg > 0 THEN
        l_drift_pct := ABS(ROUND(((l_curr_avg - l_hist_avg) / l_hist_avg) * 100, 4));
      ELSE
        l_drift_pct := 0;
      END IF;
    EXCEPTION
      WHEN OTHERS THEN
        l_drift_pct := 0;
    END;
    l_drift_score := LEAST(l_drift_pct, 100);

    l_score := GREATEST(0, ROUND(100 - (l_null_rate * 0.35) - (l_dup_rate * 0.35) - (l_out_rate * 0.20) - (l_drift_score * 0.10), 2));

    l_sev_rank := severity_rank(l_worst_sev);
    l_worst_sev := severity_name(l_sev_rank);

    INSERT INTO DQ_RUN_HISTORY$(
      owner_name,
      table_name,
      run_ts,
      quality_score,
      null_rate_pct,
      duplicate_rate_pct,
      outlier_rate_pct,
      drift_score_pct,
      worst_severity,
      details
    ) VALUES (
      UPPER(owner_name),
      UPPER(table_name),
      SYSTIMESTAMP,
      l_score,
      l_null_rate,
      l_dup_rate,
      l_out_rate,
      l_drift_score,
      l_worst_sev,
      JSON_OBJECT('source' VALUE 'evaluate_quality_score v1')
    ) RETURNING run_id INTO l_run_id;

    l_obj.put('status', 'ok');
    l_obj.put('owner_name', UPPER(owner_name));
    l_obj.put('table_name', UPPER(table_name));
    l_obj.put('run_id', l_run_id);
    l_obj.put('quality_score', l_score);
    l_obj.put('worst_severity', l_worst_sev);
    l_obj.put('components', JSON_OBJECT(
      'null_rate_pct' VALUE l_null_rate,
      'duplicate_rate_pct' VALUE l_dup_rate,
      'outlier_rate_pct' VALUE l_out_rate,
      'drift_score_pct' VALUE l_drift_score
    ));
    RETURN l_obj.to_clob;
  EXCEPTION
    WHEN OTHERS THEN
      RETURN JSON_OBJECT('status' VALUE 'error',
                         'message' VALUE ('evaluate_quality_score failed: ' || SQLERRM));
  END evaluate_quality_score;

  FUNCTION list_quality_issues(
    p_owner_name     IN VARCHAR2,
    p_table_name     IN VARCHAR2,
    p_severity_level IN VARCHAR2 DEFAULT NULL
  ) RETURN CLOB IS
    l_arr JSON_ARRAY_T := JSON_ARRAY_T();
    l_obj JSON_OBJECT_T := JSON_OBJECT_T();
  BEGIN
    ensure_internal_tables;

    FOR r IN (
      SELECT issue_id,
             issue_type,
             column_name,
             severity,
             issue_value,
             threshold_value,
             recommendation,
             generated_fix_sql,
             status,
             created_at
      FROM DQ_FINDINGS$
      WHERE owner_name = UPPER(p_owner_name)
        AND table_name = UPPER(p_table_name)
        AND (p_severity_level IS NULL OR UPPER(severity) = UPPER(p_severity_level))
      ORDER BY created_at DESC
      FETCH FIRST 100 ROWS ONLY
    ) LOOP
      l_arr.append(JSON_OBJECT(
        'issue_id' VALUE r.issue_id,
        'issue_type' VALUE r.issue_type,
        'column_name' VALUE r.column_name,
        'severity' VALUE r.severity,
        'issue_value' VALUE r.issue_value,
        'threshold_value' VALUE r.threshold_value,
        'recommendation' VALUE r.recommendation,
        'generated_fix_sql' VALUE r.generated_fix_sql,
        'status' VALUE r.status,
        'created_at' VALUE TO_CHAR(r.created_at, 'YYYY-MM-DD"T"HH24:MI:SS')
      ));
    END LOOP;

    l_obj.put('status', 'ok');
    l_obj.put('owner_name', UPPER(p_owner_name));
    l_obj.put('table_name', UPPER(p_table_name));
    l_obj.put('issues', l_arr);
    RETURN l_obj.to_clob;
  EXCEPTION
    WHEN OTHERS THEN
      RETURN JSON_OBJECT('status' VALUE 'error',
                         'message' VALUE ('list_quality_issues failed: ' || SQLERRM));
  END list_quality_issues;

  FUNCTION suggest_remediation(
    owner_name IN VARCHAR2,
    table_name IN VARCHAR2
  ) RETURN CLOB IS
    l_arr JSON_ARRAY_T := JSON_ARRAY_T();
    l_obj JSON_OBJECT_T := JSON_OBJECT_T();
  BEGIN
    ensure_internal_tables;

    l_arr.append(JSON_OBJECT(
      'issue_type' VALUE 'NULL_RATE',
      'action' VALUE 'Backfill defaults/business-safe values for null-heavy columns.',
      'sql_template' VALUE ('UPDATE ' || UPPER(owner_name) || '.' || UPPER(table_name) ||
        ' SET <column_name> = <default_value> WHERE <column_name> IS NULL')
    ));

    l_arr.append(JSON_OBJECT(
      'issue_type' VALUE 'DUPLICATE_RATE',
      'action' VALUE 'Deduplicate using row_number over key columns and keep latest record.',
      'sql_template' VALUE ('DELETE FROM ' || UPPER(owner_name) || '.' || UPPER(table_name) ||
        ' t WHERE ROWID IN (SELECT rid FROM (SELECT ROWID rid, ROW_NUMBER() OVER (PARTITION BY <key_columns> ORDER BY <updated_col> DESC) rn FROM ' ||
        UPPER(owner_name) || '.' || UPPER(table_name) || ') WHERE rn > 1)')
    ));

    l_arr.append(JSON_OBJECT(
      'issue_type' VALUE 'OUTLIER_RATE',
      'action' VALUE 'Cap or isolate outliers based on statistical bounds and business rules.',
      'sql_template' VALUE ('SELECT * FROM ' || UPPER(owner_name) || '.' || UPPER(table_name) ||
        ' WHERE ABS((<metric_col> - <mean>) / NULLIF(<stddev>,0)) > 3')
    ));

    l_obj.put('status', 'ok');
    l_obj.put('owner_name', UPPER(owner_name));
    l_obj.put('table_name', UPPER(table_name));
    l_obj.put('recommendations', l_arr);
    RETURN l_obj.to_clob;
  END suggest_remediation;

  FUNCTION apply_remediation(
    p_owner_name   IN VARCHAR2,
    p_table_name   IN VARCHAR2,
    p_issue_id     IN NUMBER,
    p_execute_mode IN VARCHAR2 DEFAULT 'PREVIEW',
    p_approval_code IN VARCHAR2 DEFAULT NULL
  ) RETURN CLOB IS
    l_sql      CLOB;
    l_mode     VARCHAR2(30) := UPPER(NVL(p_execute_mode, 'PREVIEW'));
    l_required_approval CLOB;
    l_rows     NUMBER := 0;
    l_savepoint_set BOOLEAN := FALSE;
  BEGIN
    ensure_internal_tables;

    SELECT generated_fix_sql
      INTO l_sql
      FROM DQ_FINDINGS$
      WHERE issue_id = p_issue_id
        AND owner_name = UPPER(p_owner_name)
        AND table_name = UPPER(p_table_name);

    IF l_mode = 'APPLY' THEN
      l_required_approval := get_cfg_value('REMEDIATION_APPROVAL_CODE');
      IF NVL(TRIM(l_required_approval), 'APPROVED') <> NVL(TRIM(p_approval_code), 'NO_APPROVAL') THEN
        RETURN JSON_OBJECT(
                 'status' VALUE 'error',
                 'execute_mode' VALUE l_mode,
                 'message' VALUE 'Approval code mismatch. Execution blocked.',
                 'hint' VALUE 'Set SELECTAI_AGENT_CONFIG key REMEDIATION_APPROVAL_CODE for AGENT=DATA_QUALITY, then pass matching approval code.'
               );
      END IF;

      IF l_sql IS NULL THEN
        RETURN JSON_OBJECT('status' VALUE 'error',
                           'message' VALUE 'No generated_fix_sql available for this issue.');
      END IF;

      IF NOT is_safe_remediation_sql(l_sql, p_owner_name, p_table_name) THEN
        RETURN JSON_OBJECT(
                 'status' VALUE 'error',
                 'execute_mode' VALUE l_mode,
                 'message' VALUE 'Unsafe remediation SQL blocked by policy.',
                 'policy' VALUE 'Only single-statement UPDATE/DELETE/MERGE on target table is allowed; DDL/comments/multi-statement are blocked.',
                 'preview_sql' VALUE l_sql
               );
      END IF;

      SAVEPOINT dq_apply_start;
      l_savepoint_set := TRUE;
      EXECUTE IMMEDIATE l_sql;
      l_rows := SQL%ROWCOUNT;

      UPDATE DQ_FINDINGS$
         SET status = 'RESOLVED'
       WHERE issue_id = p_issue_id;

      RETURN JSON_OBJECT('status' VALUE 'ok',
                         'execute_mode' VALUE l_mode,
                         'rows_affected' VALUE l_rows,
                         'message' VALUE 'Remediation applied successfully.');
    END IF;

    RETURN JSON_OBJECT('status' VALUE 'ok',
                       'execute_mode' VALUE l_mode,
                       'preview_sql' VALUE l_sql,
                       'message' VALUE 'Preview mode only. Re-run with execute_mode=APPLY and approval_code to execute.');
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      RETURN JSON_OBJECT('status' VALUE 'error',
                         'message' VALUE 'Issue not found for the given table/scope.');
    WHEN OTHERS THEN
      IF l_savepoint_set THEN
        ROLLBACK TO dq_apply_start;
      END IF;
      RETURN JSON_OBJECT('status' VALUE 'error',
                         'message' VALUE ('apply_remediation failed: ' || SQLERRM));
  END apply_remediation;

  FUNCTION setup_oml_data_monitoring(
    p_monitor_name IN VARCHAR2,
    p_target_schema IN VARCHAR2,
    p_target_table IN VARCHAR2,
    p_baseline_expr IN VARCHAR2,
    p_newdata_expr IN VARCHAR2
  ) RETURN CLOB IS
    l_endpoint CLOB;
    l_cred     CLOB;
    l_uri      VARCHAR2(4000);
    l_body     CLOB;
    l_resp     DBMS_CLOUD_TYPES.resp;
    l_resp_txt CLOB;
    l_job_id   VARCHAR2(256);
  BEGIN
    ensure_internal_tables;
    l_endpoint := get_cfg_value('OML_MONITORING_ENDPOINT');
    l_cred := get_cfg_value('OML_MONITORING_CREDENTIAL');

    IF l_endpoint IS NULL OR l_cred IS NULL THEN
      RETURN JSON_OBJECT(
               'status' VALUE 'error',
               'message' VALUE 'OML monitoring config missing.',
               'required_keys' VALUE JSON_ARRAY('OML_MONITORING_ENDPOINT', 'OML_MONITORING_CREDENTIAL'),
               'agent' VALUE 'DATA_QUALITY'
             );
    END IF;

    l_uri := RTRIM(l_endpoint, '/') || '/omlmod/v1/jobs';
    l_body := JSON_OBJECT(
      'jobName' VALUE p_monitor_name,
      'jobType' VALUE 'DATA_MONITORING',
      'baselineDataQuery' VALUE p_baseline_expr,
      'newDataQuery' VALUE p_newdata_expr,
      'targetTable' VALUE UPPER(p_target_schema) || '.' || UPPER(p_target_table)
    );

    l_resp := DBMS_CLOUD.SEND_REQUEST(
      credential_name => l_cred,
      uri             => l_uri,
      method          => DBMS_CLOUD.METHOD_POST,
      body            => UTL_RAW.CAST_TO_RAW(l_body)
    );
    l_resp_txt := DBMS_CLOUD.GET_RESPONSE_TEXT(l_resp);

    BEGIN
      l_job_id := JSON_VALUE(l_resp_txt, '$.jobId');
    EXCEPTION
      WHEN OTHERS THEN
        l_job_id := NULL;
    END;

    MERGE INTO DQ_OML_MONITORS$ t
    USING (
      SELECT UPPER(p_monitor_name) monitor_name FROM dual
    ) s
    ON (t.monitor_name = s.monitor_name)
    WHEN MATCHED THEN
      UPDATE SET
        t.target_schema = UPPER(p_target_schema),
        t.target_table = UPPER(p_target_table),
        t.baseline_expr = p_baseline_expr,
        t.newdata_expr = p_newdata_expr,
        t.oml_job_id = l_job_id,
        t.status = 'REGISTERED',
        t.last_run_ts = SYSTIMESTAMP,
        t.last_run_response = l_resp_txt
    WHEN NOT MATCHED THEN
      INSERT (monitor_name, target_schema, target_table, baseline_expr, newdata_expr, oml_job_id, status, last_run_ts, last_run_response)
      VALUES (UPPER(p_monitor_name), UPPER(p_target_schema), UPPER(p_target_table), p_baseline_expr, p_newdata_expr, l_job_id, 'REGISTERED', SYSTIMESTAMP, l_resp_txt);

    RETURN JSON_OBJECT(
             'status' VALUE 'ok',
             'monitor_name' VALUE UPPER(p_monitor_name),
             'job_id' VALUE l_job_id,
             'response' VALUE l_resp_txt
           );
  EXCEPTION
    WHEN OTHERS THEN
      RETURN JSON_OBJECT('status' VALUE 'error',
                         'message' VALUE ('setup_oml_data_monitoring failed: ' || SQLERRM));
  END setup_oml_data_monitoring;

  FUNCTION run_oml_data_monitoring(
    p_monitor_name IN VARCHAR2
  ) RETURN CLOB IS
    l_endpoint CLOB;
    l_cred     CLOB;
    l_job_id   VARCHAR2(256);
    l_uri      VARCHAR2(4000);
    l_resp     DBMS_CLOUD_TYPES.resp;
    l_resp_txt CLOB;
  BEGIN
    ensure_internal_tables;
    l_endpoint := get_cfg_value('OML_MONITORING_ENDPOINT');
    l_cred := get_cfg_value('OML_MONITORING_CREDENTIAL');

    IF l_endpoint IS NULL OR l_cred IS NULL THEN
      RETURN JSON_OBJECT('status' VALUE 'error',
                         'message' VALUE 'OML monitoring config missing in SELECTAI_AGENT_CONFIG for AGENT=DATA_QUALITY.');
    END IF;

    SELECT oml_job_id
      INTO l_job_id
      FROM DQ_OML_MONITORS$
     WHERE monitor_name = UPPER(p_monitor_name);

    IF l_job_id IS NULL THEN
      RETURN JSON_OBJECT('status' VALUE 'error',
                         'message' VALUE 'No OML job id mapped for this monitor. Run setup first.');
    END IF;

    l_uri := RTRIM(l_endpoint, '/') || '/omlmod/v1/jobs/' || UTL_URL.ESCAPE(l_job_id, TRUE) || '/run';
    l_resp := DBMS_CLOUD.SEND_REQUEST(
      credential_name => l_cred,
      uri             => l_uri,
      method          => DBMS_CLOUD.METHOD_POST
    );
    l_resp_txt := DBMS_CLOUD.GET_RESPONSE_TEXT(l_resp);

    UPDATE DQ_OML_MONITORS$
       SET status = 'RUN_TRIGGERED',
           last_run_ts = SYSTIMESTAMP,
           last_run_response = l_resp_txt
     WHERE monitor_name = UPPER(p_monitor_name);

    RETURN JSON_OBJECT(
             'status' VALUE 'ok',
             'monitor_name' VALUE UPPER(p_monitor_name),
             'job_id' VALUE l_job_id,
             'response' VALUE l_resp_txt
           );
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      RETURN JSON_OBJECT('status' VALUE 'error',
                         'message' VALUE 'Monitor not found. Run setup_oml_data_monitoring first.');
    WHEN OTHERS THEN
      RETURN JSON_OBJECT('status' VALUE 'error',
                         'message' VALUE ('run_oml_data_monitoring failed: ' || SQLERRM));
  END run_oml_data_monitoring;
END database_quality;
/

CREATE OR REPLACE PACKAGE select_ai_data_quality_agent AS
  FUNCTION profile_table(
    owner_name  VARCHAR2,
    table_name  VARCHAR2,
    sample_rows NUMBER DEFAULT 10000
  ) RETURN CLOB;

  FUNCTION detect_nulls(
    owner_name VARCHAR2,
    table_name VARCHAR2
  ) RETURN CLOB;

  FUNCTION detect_duplicates(
    owner_name      VARCHAR2,
    table_name      VARCHAR2,
    key_columns_csv VARCHAR2 DEFAULT NULL
  ) RETURN CLOB;

  FUNCTION detect_outliers(
    owner_name VARCHAR2,
    table_name VARCHAR2,
    z_limit    NUMBER DEFAULT 3
  ) RETURN CLOB;

  FUNCTION detect_drift(
    owner_name      VARCHAR2,
    table_name      VARCHAR2,
    baseline_days   NUMBER DEFAULT 30,
    current_days    NUMBER DEFAULT 7,
    drift_threshold NUMBER DEFAULT 20
  ) RETURN CLOB;

  FUNCTION generate_quality_rules(
    owner_name VARCHAR2,
    table_name VARCHAR2
  ) RETURN CLOB;

  FUNCTION evaluate_quality_score(
    owner_name VARCHAR2,
    table_name VARCHAR2
  ) RETURN CLOB;

  FUNCTION list_quality_issues(
    owner_name     VARCHAR2,
    table_name     VARCHAR2,
    severity_level VARCHAR2 DEFAULT NULL
  ) RETURN CLOB;

  FUNCTION suggest_remediation(
    owner_name VARCHAR2,
    table_name VARCHAR2
  ) RETURN CLOB;

  FUNCTION apply_remediation(
    owner_name   VARCHAR2,
    table_name   VARCHAR2,
    issue_id     NUMBER,
    execute_mode VARCHAR2 DEFAULT 'PREVIEW',
    approval_code VARCHAR2 DEFAULT NULL
  ) RETURN CLOB;

  FUNCTION setup_oml_data_monitoring(
    monitor_name IN VARCHAR2,
    target_schema IN VARCHAR2,
    target_table IN VARCHAR2,
    baseline_expr IN VARCHAR2,
    newdata_expr IN VARCHAR2
  ) RETURN CLOB;

  FUNCTION run_oml_data_monitoring(
    monitor_name IN VARCHAR2
  ) RETURN CLOB;
END select_ai_data_quality_agent;
/

CREATE OR REPLACE PACKAGE BODY select_ai_data_quality_agent AS
  FUNCTION profile_table(
    owner_name  VARCHAR2,
    table_name  VARCHAR2,
    sample_rows NUMBER DEFAULT 10000
  ) RETURN CLOB IS
  BEGIN
    RETURN database_quality.profile_table(owner_name, table_name, sample_rows);
  END profile_table;

  FUNCTION detect_nulls(owner_name VARCHAR2, table_name VARCHAR2) RETURN CLOB IS
  BEGIN
    RETURN database_quality.detect_nulls(owner_name, table_name);
  END detect_nulls;

  FUNCTION detect_duplicates(
    owner_name      VARCHAR2,
    table_name      VARCHAR2,
    key_columns_csv VARCHAR2 DEFAULT NULL
  ) RETURN CLOB IS
  BEGIN
    RETURN database_quality.detect_duplicates(owner_name, table_name, key_columns_csv);
  END detect_duplicates;

  FUNCTION detect_outliers(
    owner_name VARCHAR2,
    table_name VARCHAR2,
    z_limit    NUMBER DEFAULT 3
  ) RETURN CLOB IS
  BEGIN
    RETURN database_quality.detect_outliers(owner_name, table_name, z_limit);
  END detect_outliers;

  FUNCTION detect_drift(
    owner_name      VARCHAR2,
    table_name      VARCHAR2,
    baseline_days   NUMBER DEFAULT 30,
    current_days    NUMBER DEFAULT 7,
    drift_threshold NUMBER DEFAULT 20
  ) RETURN CLOB IS
  BEGIN
    RETURN database_quality.detect_drift(owner_name, table_name, baseline_days, current_days, drift_threshold);
  END detect_drift;

  FUNCTION generate_quality_rules(owner_name VARCHAR2, table_name VARCHAR2) RETURN CLOB IS
  BEGIN
    RETURN database_quality.generate_quality_rules(owner_name, table_name);
  END generate_quality_rules;

  FUNCTION evaluate_quality_score(owner_name VARCHAR2, table_name VARCHAR2) RETURN CLOB IS
  BEGIN
    RETURN database_quality.evaluate_quality_score(owner_name, table_name);
  END evaluate_quality_score;

  FUNCTION list_quality_issues(
    owner_name     VARCHAR2,
    table_name     VARCHAR2,
    severity_level VARCHAR2 DEFAULT NULL
  ) RETURN CLOB IS
  BEGIN
    RETURN database_quality.list_quality_issues(owner_name, table_name, severity_level);
  END list_quality_issues;

  FUNCTION suggest_remediation(owner_name VARCHAR2, table_name VARCHAR2) RETURN CLOB IS
  BEGIN
    RETURN database_quality.suggest_remediation(owner_name, table_name);
  END suggest_remediation;

  FUNCTION apply_remediation(
    owner_name   VARCHAR2,
    table_name   VARCHAR2,
    issue_id     NUMBER,
    execute_mode VARCHAR2 DEFAULT 'PREVIEW',
    approval_code VARCHAR2 DEFAULT NULL
  ) RETURN CLOB IS
  BEGIN
    RETURN database_quality.apply_remediation(owner_name, table_name, issue_id, execute_mode, approval_code);
  END apply_remediation;

  FUNCTION setup_oml_data_monitoring(
    monitor_name IN VARCHAR2,
    target_schema IN VARCHAR2,
    target_table IN VARCHAR2,
    baseline_expr IN VARCHAR2,
    newdata_expr IN VARCHAR2
  ) RETURN CLOB IS
  BEGIN
    RETURN database_quality.setup_oml_data_monitoring(monitor_name, target_schema, target_table, baseline_expr, newdata_expr);
  END setup_oml_data_monitoring;

  FUNCTION run_oml_data_monitoring(
    monitor_name IN VARCHAR2
  ) RETURN CLOB IS
  BEGIN
    RETURN database_quality.run_oml_data_monitoring(monitor_name);
  END run_oml_data_monitoring;
END select_ai_data_quality_agent;
/

CREATE OR REPLACE PROCEDURE initialize_data_quality_tools
IS
  PROCEDURE drop_tool_if_exists(p_tool_name IN VARCHAR2) IS
    l_tool_count NUMBER;
  BEGIN
    SELECT COUNT(*)
      INTO l_tool_count
      FROM USER_AI_AGENT_TOOLS
      WHERE TOOL_NAME = p_tool_name;

    IF l_tool_count > 0 THEN
      DBMS_CLOUD_AI_AGENT.DROP_TOOL(p_tool_name);
    END IF;
  END drop_tool_if_exists;
BEGIN
  drop_tool_if_exists('PROFILE_TABLE_TOOL');
  DBMS_CLOUD_AI_AGENT.CREATE_TOOL(
    tool_name => 'PROFILE_TABLE_TOOL',
    attributes => '{"instruction":"Profile a table for baseline data quality metrics.","function":"select_ai_data_quality_agent.profile_table"}',
    description => 'Profile a table for data quality'
  );

  drop_tool_if_exists('DETECT_NULLS_TOOL');
  DBMS_CLOUD_AI_AGENT.CREATE_TOOL(
    tool_name => 'DETECT_NULLS_TOOL',
    attributes => '{"instruction":"Detect null-heavy columns and null rates.","function":"select_ai_data_quality_agent.detect_nulls"}',
    description => 'Detect null issues'
  );

  drop_tool_if_exists('DETECT_DUPLICATES_TOOL');
  DBMS_CLOUD_AI_AGENT.CREATE_TOOL(
    tool_name => 'DETECT_DUPLICATES_TOOL',
    attributes => '{"instruction":"Detect duplicates using all columns or provided key columns.","function":"select_ai_data_quality_agent.detect_duplicates"}',
    description => 'Detect duplicate records'
  );

  drop_tool_if_exists('DETECT_OUTLIERS_TOOL');
  DBMS_CLOUD_AI_AGENT.CREATE_TOOL(
    tool_name => 'DETECT_OUTLIERS_TOOL',
    attributes => '{"instruction":"Detect numeric outliers using z-score.","function":"select_ai_data_quality_agent.detect_outliers"}',
    description => 'Detect outliers'
  );

  drop_tool_if_exists('DETECT_DRIFT_TOOL');
  DBMS_CLOUD_AI_AGENT.CREATE_TOOL(
    tool_name => 'DETECT_DRIFT_TOOL',
    attributes => '{"instruction":"Detect quality-score drift from baseline history.","function":"select_ai_data_quality_agent.detect_drift"}',
    description => 'Detect data quality drift'
  );

  drop_tool_if_exists('GENERATE_QUALITY_RULES_TOOL');
  DBMS_CLOUD_AI_AGENT.CREATE_TOOL(
    tool_name => 'GENERATE_QUALITY_RULES_TOOL',
    attributes => '{"instruction":"Generate recommended quality rules for the table.","function":"select_ai_data_quality_agent.generate_quality_rules"}',
    description => 'Generate quality rules'
  );

  drop_tool_if_exists('EVALUATE_QUALITY_SCORE_TOOL');
  DBMS_CLOUD_AI_AGENT.CREATE_TOOL(
    tool_name => 'EVALUATE_QUALITY_SCORE_TOOL',
    attributes => '{"instruction":"Compute and store the overall quality score for a table.","function":"select_ai_data_quality_agent.evaluate_quality_score"}',
    description => 'Evaluate quality score'
  );

  drop_tool_if_exists('LIST_QUALITY_ISSUES_TOOL');
  DBMS_CLOUD_AI_AGENT.CREATE_TOOL(
    tool_name => 'LIST_QUALITY_ISSUES_TOOL',
    attributes => '{"instruction":"List open quality issues and severity.","function":"select_ai_data_quality_agent.list_quality_issues"}',
    description => 'List quality issues'
  );

  drop_tool_if_exists('SUGGEST_REMEDIATION_TOOL');
  DBMS_CLOUD_AI_AGENT.CREATE_TOOL(
    tool_name => 'SUGGEST_REMEDIATION_TOOL',
    attributes => '{"instruction":"Suggest remediation actions and SQL templates.","function":"select_ai_data_quality_agent.suggest_remediation"}',
    description => 'Suggest remediation'
  );

  drop_tool_if_exists('APPLY_REMEDIATION_TOOL');
  DBMS_CLOUD_AI_AGENT.CREATE_TOOL(
    tool_name => 'APPLY_REMEDIATION_TOOL',
    attributes => '{"instruction":"Preview or apply generated remediation SQL for a known issue. APPLY requires approval_code.","function":"select_ai_data_quality_agent.apply_remediation"}',
    description => 'Apply remediation for a quality issue'
  );

  drop_tool_if_exists('SETUP_OML_DATA_MONITORING_TOOL');
  DBMS_CLOUD_AI_AGENT.CREATE_TOOL(
    tool_name => 'SETUP_OML_DATA_MONITORING_TOOL',
    attributes => '{"instruction":"Create/register an OML Services data monitoring job for a table using baseline/new-data SQL expressions.","function":"select_ai_data_quality_agent.setup_oml_data_monitoring"}',
    description => 'Setup OML Services data monitoring'
  );

  drop_tool_if_exists('RUN_OML_DATA_MONITORING_TOOL');
  DBMS_CLOUD_AI_AGENT.CREATE_TOOL(
    tool_name => 'RUN_OML_DATA_MONITORING_TOOL',
    attributes => '{"instruction":"Trigger a previously registered OML Services data monitoring job run.","function":"select_ai_data_quality_agent.run_oml_data_monitoring"}',
    description => 'Run OML Services data monitoring'
  );

  DBMS_OUTPUT.PUT_LINE('initialize_data_quality_tools completed.');
END initialize_data_quality_tools;
/

BEGIN
  initialize_data_quality_tools;
END;
/

ALTER SESSION SET CURRENT_SCHEMA = ADMIN;

PROMPT DATA_QUALITY agent tools installation completed
